DROP SCHEMA IF EXISTS wisdom cascade;
CREATE SCHEMA wisdom;
CREATE TABLE wisdom.notes (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title VARCHAR(120) NOT NULL,
                     content TEXT,
                     CHECK (char_length(content) <= 10000),
                     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                     updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

INSERT INTO wisdom.notes (title, content) VALUES ('Meeting notes', 'Discussed roadmap, deadlines and next steps. Action items assigned.');
INSERT INTO wisdom.notes (title, content) VALUES ('Ideas for blog', 'Topics: TypeScript tips, React performance, Spring Boot testing.');
INSERT INTO wisdom.notes (title, content) VALUES ('Shopping list', 'Milk, eggs, bread, olive oil, fresh herbs.');
INSERT INTO wisdom.notes (title, content) VALUES ('Draft: feature spec', 'Add partition-aware API service; include token handling and retries.');
INSERT INTO wisdom.notes (title, content) VALUES ('Research links', 'Collect papers on time-series DBs, Postgres performance and best practices.');
INSERT INTO wisdom.notes (title, content) VALUES ('Personal goal', 'Read one technical book per month and practice coding katas weekly.');
INSERT INTO wisdom.notes (title, content) VALUES ('Deployment checklist', 'Run tests, build artifacts, migrate DB, deploy to staging, smoke test, deploy to production.');
INSERT INTO wisdom.notes (title, content) VALUES ('Bug notes', 'Null pointer in user profile when email is missing. Reproduce steps and add guard.');
INSERT INTO wisdom.notes (title, content) VALUES ('Refactor plan', 'Extract api-service helpers, improve typing, add unit tests and integration tests.');
INSERT INTO wisdom.notes (title, content) VALUES ('Conference talk', 'Prepare slides about full-stack type safety: Java, Spring Boot, TypeScript and React.');
INSERT INTO wisdom.notes (title, content) VALUES ('Optimization ideas', 'Use connection pooling, tune indexes, avoid sequential scans on large tables.');
INSERT INTO wisdom.notes (title, content) VALUES ('Onboarding', 'Create README, architecture diagram and example requests for new team members.');
INSERT INTO wisdom.notes (title, content) VALUES ('Weekly retrospective', 'What went well: delivery. What to improve: testing coverage and CI speed.');
INSERT INTO wisdom.notes (title, content) VALUES ('Backup note', 'Ensure daily DB backups and periodic restore tests are scheduled.');
INSERT INTO wisdom.notes (title, content) VALUES ('Long content example', 'This is a longer note to illustrate storing larger text: it contains a few paragraphs of details about migration steps, risk assessment, rollback plan and monitoring requirements. Keep content under the 10000 character limit.');

CREATE INDEX IF NOT EXISTS idx_note_updated_at ON wisdom.note (updated_at);
$BODY$;
